export const onlineItems = [
  {
    id: '1697951000000302286',
    title: 'ALMOND PISTA COOKIES 250GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'ALMOND PISTA COOKIES 250GM',
        url: '/assets/onlineItemImages/COOKIES_MAIN.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'ALMOND PISTA COOKIES 250GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '120.00',
    slug: '1697951000000302286',
    stock: 0,
  },
  {
    id: '1697951000000302325',
    title: 'ALMOND PISTA COOKIES 400GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'ALMOND PISTA COOKIES 400GM',
        url: '/assets/onlineItemImages/COOKIES_MAIN.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'ALMOND PISTA COOKIES 400GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '240.00',
    slug: '1697951000000302325',
    stock: 3,
  },
  {
    id: '1697951000000302403',
    title: 'BUTTER COOKIES 250GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'BUTTER COOKIES 250GM',
        url: '/assets/onlineItemImages/ButterCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'BUTTER COOKIES 250GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '120.00',
    slug: '1697951000000302403',
    stock: 0,
  },
  {
    id: '1697951000000302442',
    title: 'BUTTER COOKIES 400GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'BUTTER COOKIES 400GM',
        url: '/assets/onlineItemImages/ButterCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'BUTTER COOKIES 400GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '240.00',
    slug: '1697951000000302442',
    stock: 2,
  },
  {
    id: '1697951000000302481',
    title: 'CHOCOCHIP COOKIES 400GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CHOCOCHIP COOKIES 400GM',
        url: '/assets/onlineItemImages/ChocoChipCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CHOCOCHIP COOKIES 400GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '240.00',
    slug: '1697951000000302481',
    stock: 1,
  },
  {
    id: '1697951000000302520',
    title: 'CHOCOCHIPS COOKIES 250GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CHOCOCHIPS COOKIES 250GM',
        url: '/assets/onlineItemImages/ChocoChipCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CHOCOCHIPS COOKIES 250GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '120.00',
    slug: '1697951000000302520',
    stock: 0,
  },
  {
    id: '1697951000000302559',
    title: 'COCONUT COOKIES 250GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'COCONUT COOKIES 250GM',
        url: '/assets/onlineItemImages/Coconut.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'COCONUT COOKIES 250GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '120.00',
    slug: '1697951000000302559',
    stock: 0,
  },
  {
    id: '1697951000000302598',
    title: 'SWEET AND SALT COOKIES 250 GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SWEET AND SALT COOKIES 250 GM',
        url: '/assets/onlineItemImages/SweetAndSalt.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SWEET AND SALT COOKIES 250 GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '120.00',
    slug: '1697951000000302598',
    stock: 0,
  },
  {
    id: '1697951000000302637',
    title: 'TEA COOKIES 250GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'TEA COOKIES 250GM',
        url: '/assets/onlineItemImages/TeaCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'TEA COOKIES 250GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '120.00',
    slug: '1697951000000302637',
    stock: 0,
  },
  {
    id: '1697951000000302676',
    title: 'TEA COOKIES 400GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'TEA COOKIES 400GM',
        url: '/assets/onlineItemImages/TeaCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'TEA COOKIES 400GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '240.00',
    slug: '1697951000000302676',
    stock: 1,
  },
  {
    id: '1697951000000302715',
    title: 'Corn Flakes(250 GM)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'Corn Flakes(250 GM)',
        url: '/assets/onlineItemImages/CornFlakes.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'Corn Flakes(250 GM)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '85.00',
    slug: '1697951000000302715',
    stock: 2,
  },
  {
    id: '1697951000000302754',
    title: 'CRISPY CHOCO BITES(250GM)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CRISPY CHOCO BITES(250GM)',
        url: '/assets/onlineItemImages/ChocoBites.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CRISPY CHOCO BITES(250GM)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '115.00',
    slug: '1697951000000302754',
    stock: 0,
  },
  {
    id: '1697951000000302793',
    title: 'CRISPY CHOCO BITES 27GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CRISPY CHOCO BITES 27GM',
        url: '/assets/onlineItemImages/ChocoBites.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CRISPY CHOCO BITES 27GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '10.00',
    slug: '1697951000000302793',
    stock: 0,
  },
  {
    id: '1697951000000302832',
    title: 'Crunchy Muesli(500GM)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'Crunchy Muesli(500GM)',
        url: '/assets/onlineItemImages/Muesli.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'Crunchy Muesli(500GM)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '300.00',
    slug: '1697951000000302832',
    stock: 0,
  },
  {
    id: '1697951000000302871',
    title: 'ORIGINAL OATS 450GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'ORIGINAL OATS 450GM',
        url: '/assets/onlineItemImages/OATS.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'ORIGINAL OATS 450GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '130.00',
    slug: '1697951000000302871',
    stock: 5,
  },
  {
    id: '1697951000000302910',
    title: 'ORIGINAL OATS 900GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'ORIGINAL OATS 900GM',
        url: '/assets/onlineItemImages/OATS.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'ORIGINAL OATS 900GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '240.00',
    slug: '1697951000000302910',
    stock: 2,
  },
  {
    id: '1697951000000302949',
    title: 'CORN FLAKES 70GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CORN FLAKES 70GM',
        url: '/assets/onlineItemImages/CornFlakes.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CORN FLAKES 70GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '20.00',
    slug: '1697951000000302949',
    stock: 0,
  },
  {
    id: '1697951000000302988',
    title: 'Chapati Flour (500gm)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'Chapati Flour (500gm)',
        url: '/assets/onlineItemImages/chapatiflour.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'Chapati Flour (500gm)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '150.00',
    slug: '1697951000000302988',
    stock: 0,
  },
  {
    id: '1697951000000303027',
    title: 'BUTTER COOKIES 250GM (M C)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'BUTTER COOKIES 250GM (M C)',
        url: '/assets/onlineItemImages/ButterCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'BUTTER COOKIES 250GM (M C)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '100.00',
    slug: '1697951000000303027',
    stock: 0,
  },
  {
    id: '1697951000000303066',
    title: 'COCONUT COOKIES 250GM (M C)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'COCONUT COOKIES 250GM (M C)',
        url: '/assets/onlineItemImages/Coconut.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'COCONUT COOKIES 250GM (M C)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '100.00',
    slug: '1697951000000303066',
    stock: 0,
  },
  {
    id: '1697951000000303105',
    title: 'SWEET & SALT COOKIES 250GM (M C)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SWEET & SALT COOKIES 250GM (M C)',
        url: '/assets/onlineItemImages/SweetAndSalt.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SWEET & SALT COOKIES 250GM (M C)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '100.00',
    slug: '1697951000000303105',
    stock: 3,
  },
  {
    id: '1697951000000303144',
    title: 'TEA COOKIES 250GM (M C)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'TEA COOKIES 250GM (M C)',
        url: '/assets/onlineItemImages/TeaCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'TEA COOKIES 250GM (M C)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '100.00',
    slug: '1697951000000303144',
    stock: 5,
  },
  {
    id: '1697951000000303183',
    title: 'ALMOND PISTA COOKIES 250GM(M C)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'ALMOND PISTA COOKIES 250GM(M C)',
        url: '/assets/onlineItemImages/COOKIES_MAIN.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'ALMOND PISTA COOKIES 250GM(M C)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '100.00',
    slug: '1697951000000303183',
    stock: 0,
  },
  {
    id: '1697951000000303222',
    title: 'CHOCOCHIPS COOKIES 250GM(M C)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CHOCOCHIPS COOKIES 250GM(M C)',
        url: '/assets/onlineItemImages/ChocoChipCookies.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CHOCOCHIPS COOKIES 250GM(M C)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '100.00',
    slug: '1697951000000303222',
    stock: 0,
  },
  {
    id: '1697951000000303261',
    title: 'TANGY TAMATO MSL OATS 40GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'TANGY TAMATO MSL OATS 40GM',
        url: '/assets/onlineItemImages/tangy.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'TANGY TAMATO MSL OATS 40GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '20.00',
    slug: '1697951000000303261',
    stock: 8,
  },
  {
    id: '1697951000000303300',
    title: 'MIX VEGGIE MSL OATS 40GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'MIX VEGGIE MSL OATS 40GM',
        url: '/assets/onlineItemImages/mixoats.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'MIX VEGGIE MSL OATS 40GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '20.00',
    slug: '1697951000000303300',
    stock: 1,
  },
  {
    id: '1697951000000303339',
    title: 'WHITE SAUCE SEASONING 7GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'WHITE SAUCE SEASONING 7GM',
        url: '/assets/onlineItemImages/whitesauce.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'WHITE SAUCE SEASONING 7GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '10.00',
    slug: '1697951000000303339',
    stock: 0,
  },
  {
    id: '1697951000000303378',
    title: 'TOMATO & HERB SEASONING 7GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'TOMATO & HERB SEASONING 7GM',
        url: '/assets/onlineItemImages/tomatoherb.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'TOMATO & HERB SEASONING 7GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '10.00',
    slug: '1697951000000303378',
    stock: 13,
  },
  {
    id: '1697951000000306498',
    title: 'CHANA SATTU 200GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CHANA SATTU 200GM',
        url: '/assets/onlineItemImages/Channa_Sattu.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CHANA SATTU 200GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '70.00',
    slug: '1697951000000306498',
    stock: 0,
  },
  {
    id: '1697951000000306537',
    title: 'CHANA SATTU 500GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CHANA SATTU 500GM',
        url: '/assets/onlineItemImages/Channa_Sattu.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CHANA SATTU 500GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '150.00',
    slug: '1697951000000306537',
    stock: 4,
  },
  {
    id: '1697951000000306576',
    title: 'CHAPATI FLOUR 1KG',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CHAPATI FLOUR 1KG',
        url: '/assets/onlineItemImages/chapatiflour.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CHAPATI FLOUR 1KG',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '100.00',
    slug: '1697951000000306576',
    stock: 0,
  },
  {
    id: '1697951000000306615',
    title: 'CHUDA POWDER 500GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CHUDA POWDER 500GM',
        url: '/assets/onlineItemImages/Chudda_Powder.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CHUDA POWDER 500GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '130.00',
    slug: '1697951000000306615',
    stock: 5,
  },
  {
    id: '1697951000000306654',
    title: 'CORN FLOUR 100GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CORN FLOUR 100GM',
        url: '/assets/onlineItemImages/Corn_Flour.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CORN FLOUR 100GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '25.00',
    slug: '1697951000000306654',
    stock: 0,
  },
  {
    id: '1697951000000306693',
    title: 'CORN FLOUR 1KG',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CORN FLOUR 1KG',
        url: '/assets/onlineItemImages/Corn_Flour.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CORN FLOUR 1KG',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '120.00',
    slug: '1697951000000306693',
    stock: 0,
  },
  {
    id: '1697951000000306732',
    title: 'DALIYA 1KG',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'DALIYA 1KG',
        url: '/assets/onlineItemImages/Daliya(2).png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'DALIYA 1KG',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '130.00',
    slug: '1697951000000306732',
    stock: 0,
  },
  {
    id: '1697951000000306771',
    title: 'DALIYA 300GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'DALIYA 300GM',
        url: '/assets/onlineItemImages/Daliya(2).png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'DALIYA 300GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '50.00',
    slug: '1697951000000306771',
    stock: 0,
  },
  {
    id: '1697951000000306810',
    title: 'DALIYA 500GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'DALIYA 500GM',
        url: '/assets/onlineItemImages/Daliya(2).png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'DALIYA 500GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '70.00',
    slug: '1697951000000306810',
    stock: 0,
  },
  {
    id: '1697951000000306849',
    title: 'FRUIT RUSK 200GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'FRUIT RUSK 200GM',
        url: '/assets/onlineItemImages/fruitrusk.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'FRUIT RUSK 200GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '40.00',
    slug: '1697951000000306849',
    stock: 5,
  },
  {
    id: '1697951000000306888',
    title: 'FRUIT RUSK 60GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'FRUIT RUSK 60GM',
        url: '/assets/onlineItemImages/fruitrusk.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'FRUIT RUSK 60GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '10.00',
    slug: '1697951000000306888',
    stock: 2,
  },
  {
    id: '1697951000000306927',
    title: 'IDILI RAWA (500GM)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'IDILI RAWA (500GM)',
        url: '/assets/onlineItemImages/idli.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'IDILI RAWA (500GM)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '50.00',
    slug: '1697951000000306927',
    stock: 3,
  },
  {
    id: '1697951000000307005',
    title: 'MILK RUSK 200GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'MILK RUSK 200GM',
        url: '/assets/onlineItemImages/milkrusk.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'MILK RUSK 200GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '40.00',
    slug: '1697951000000307005',
    stock: 8,
  },
  {
    id: '1697951000000307044',
    title: 'MILK RUSK 60GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'MILK RUSK 60GM',
        url: '/assets/onlineItemImages/milkrusk.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'MILK RUSK 60GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '10.00',
    slug: '1697951000000307044',
    stock: 5,
  },
  {
    id: '1697951000000307083',
    title: 'OLIVE OIL 100ML( 1+1)PCS',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'OLIVE OIL 100ML( 1+1)PCS',
        url: '/assets/onlineItemImages/oliveoil.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'OLIVE OIL 100ML( 1+1)PCS',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '180.00',
    slug: '1697951000000307083',
    stock: 0,
  },
  {
    id: '1697951000000307122',
    title: 'OLIVE OIL 500ML (1+1) PCS',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'OLIVE OIL 500ML (1+1) PCS',
        url: '/assets/onlineItemImages/oliveoil.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'OLIVE OIL 500ML (1+1) PCS',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '800.00',
    slug: '1697951000000307122',
    stock: 2,
  },
  {
    id: '1697951000000307239',
    title: 'PUNJABI TADKA 500GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'PUNJABI TADKA 500GM',
        url: '/assets/onlineItemImages/punjabitadka.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'PUNJABI TADKA 500GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '150.00',
    slug: '1697951000000307239',
    stock: 3,
  },
  {
    id: '1697951000000307278',
    title: 'RAGI FLOUR 500GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'RAGI FLOUR 500GM',
        url: '/assets/onlineItemImages/ragiflour.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'RAGI FLOUR 500GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '75.00',
    slug: '1697951000000307278',
    stock: 2,
  },
  {
    id: '1697951000000307317',
    title: 'SAGOO BIG 200GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SAGOO BIG 200GM',
        url: '/assets/onlineItemImages/sagoo.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SAGOO BIG 200GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '40.00',
    slug: '1697951000000307317',
    stock: 0,
  },
  {
    id: '1697951000000307356',
    title: 'SAGOO BIG 450GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SAGOO BIG 450GM',
        url: '/assets/onlineItemImages/sagoo.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SAGOO BIG 450GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '99.00',
    slug: '1697951000000307356',
    stock: 10,
  },
  {
    id: '1697951000000307395',
    title: 'SAGOO SMALL 200GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SAGOO SMALL 200GM',
        url: '/assets/onlineItemImages/sagoo.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SAGOO SMALL 200GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '40.00',
    slug: '1697951000000307395',
    stock: 0,
  },
  {
    id: '1697951000000307434',
    title: 'SAGOO SMALL 500GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SAGOO SMALL 500GM',
        url: '/assets/onlineItemImages/sagoo.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SAGOO SMALL 500GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '99.00',
    slug: '1697951000000307434',
    stock: 9,
  },
  {
    id: '1697951000000307551',
    title: 'SOOJI 1KG',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SOOJI 1KG',
        url: '/assets/onlineItemImages/Sooji.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SOOJI 1KG',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '90.00',
    slug: '1697951000000307551',
    stock: 0,
  },
  {
    id: '1697951000000307590',
    title: 'SOOJI 500GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SOOJI 500GM',
        url: '/assets/onlineItemImages/Sooji.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SOOJI 500GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '50.00',
    slug: '1697951000000307590',
    stock: 6,
  },
  {
    id: '1697951000000307629',
    title: 'CUSTARD POWDER 100GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CUSTARD POWDER 100GM',
        url: '/assets/onlineItemImages/custard.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CUSTARD POWDER 100GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '55.00',
    slug: '1697951000000307629',
    stock: 0,
  },
  {
    id: '1697951000000307746',
    title: 'SOYA ROLL 200GM (BIG)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SOYA ROLL 200GM (BIG)',
        url: '/assets/onlineItemImages/soyarol.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SOYA ROLL 200GM (BIG)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '60.00',
    slug: '1697951000000307746',
    stock: 2,
  },
  {
    id: '1697951000000307785',
    title: 'SOYA ROLL 200GM (SMALL)',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SOYA ROLL 200GM (SMALL)',
        url: '/assets/onlineItemImages/soyarol.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SOYA ROLL 200GM (SMALL)',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '60.00',
    slug: '1697951000000307785',
    stock: 1,
  },
  {
    id: '1697951000000307824',
    title: 'SOYA ROLL BIG 1KG',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SOYA ROLL BIG 1KG',
        url: '/assets/onlineItemImages/soyarol.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SOYA ROLL BIG 1KG',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '200.00',
    slug: '1697951000000307824',
    stock: 3,
  },
  {
    id: '1697951000000307863',
    title: 'SOYA ROLL SMALL 1KG',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'SOYA ROLL SMALL 1KG',
        url: '/assets/onlineItemImages/soyarol.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'SOYA ROLL SMALL 1KG',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '200.00',
    slug: '1697951000000307863',
    stock: 3,
  },
  {
    id: '1697951000000308058',
    title: 'Sagoo Small 1kg',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'Sagoo Small 1kg',
        url: '/assets/onlineItemImages/sagoo.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'Sagoo Small 1kg',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '165.00',
    slug: '1697951000000308058',
    stock: 0,
  },
  {
    id: '1697951000000308136',
    title: 'Sagoo big 1kg',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'Sagoo big 1kg',
        url: '/assets/onlineItemImages/sagoo.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'Sagoo big 1kg',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '165.00',
    slug: '1697951000000308136',
    stock: 0,
  },
  {
    id: '1697951000000308175',
    title: 'CRISPY CHOCO BITES 20GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CRISPY CHOCO BITES 20GM',
        url: '/assets/onlineItemImages/ChocoBites.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CRISPY CHOCO BITES 20GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '10.00',
    slug: '1697951000000308175',
    stock: 0,
  },
  {
    id: '1697951000000308214',
    title: 'CORN FLAKES 60GM',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'CORN FLAKES 60GM',
        url: '/assets/onlineItemImages/CornFlakes.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'CORN FLAKES 60GM',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '20.00',
    slug: '1697951000000308214',
    stock: 15,
  },
  {
    id: '1697951000000311022',
    title: 'ICY LEMONADE 170ML',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'ICY LEMONADE 170ML',
        url: '/assets/onlineItemImages/lemonade.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'ICY LEMONADE 170ML',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '12.00',
    slug: '1697951000000311022',
    stock: 0,
  },
  {
    id: '1697951000000311061',
    title: 'LITCHI LUSH 170ML',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'LITCHI LUSH 170ML',
        url: '/assets/onlineItemImages/litchilush.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'LITCHI LUSH 170ML',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '12.00',
    slug: '1697951000000311061',
    stock: 45,
  },
  {
    id: '1697951000000311100',
    title: 'LITCHI LUSH 300ML',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'LITCHI LUSH 300ML',
        url: '/assets/onlineItemImages/litchilush.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'LITCHI LUSH 300ML',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '20.00',
    slug: '1697951000000311100',
    stock: 30,
  },
  {
    id: '1697951000000311139',
    title: 'PINEAPPLE BLISH 170ML',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'PINEAPPLE BLISH 170ML',
        url: '/assets/onlineItemImages/pineapple.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'PINEAPPLE BLISH 170ML',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '12.00',
    slug: '1697951000000311139',
    stock: 12,
  },
  {
    id: '1697951000000311178',
    title: 'RIPE MANGO1.2L',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'RIPE MANGO1.2L',
        url: '/assets/onlineItemImages/rasiley.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'RIPE MANGO1.2L',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '75.00',
    slug: '1697951000000311178',
    stock: 2,
  },
  {
    id: '1697951000000311217',
    title: 'RIPE MANGO 160ML',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'RIPE MANGO 160ML',
        url: '/assets/onlineItemImages/rasiley.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'RIPE MANGO 160ML',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '12.00',
    slug: '1697951000000311217',
    stock: 3,
  },
  {
    id: '1697951000000311256',
    title: 'RIPE MANGO 300ML',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'RIPE MANGO 300ML',
        url: '/assets/onlineItemImages/rasiley.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'RIPE MANGO 300ML',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '20.00',
    slug: '1697951000000311256',
    stock: 3,
  },
  {
    id: '1697951000000311295',
    title: 'RIPE MANGO 600ML',
    layout: [],
    categories: '',
    meta: {
      description: 'All items are saleable for the customer',
      image: {
        alt: 'RIPE MANGO 600ML',
        url: '/assets/onlineItemImages/rasiley.png',
        id: '1',
        updatedAt: Date.now().toString(),
        createdAt: Date.now().toString(),
      },
      title: 'RIPE MANGO 600ML',
    },
    updatedAt: Date.now().toString(),
    createdAt: Date.now().toString(),
    priceJSON: '40.00',
    slug: '1697951000000311295',
    stock: 28,
  },
]
